version: '3.1'

services:
  nginx:
    container_name: 'tap-website-reverseproxy'
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./_deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/tapsite:/etc/ssl/tapsite
      # - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      # - /docker-volumes/etc/letsencrypt/live/ohhaithere.com/fullchain.pem:/etc/letsencrypt/live/ohhaithere.com/fullchain.pem
      # - /docker-volumes/etc/letsencrypt/live/ohhaithere.com/privkey.pem:/etc/letsencrypt/live/ohhaithere.com/privkey.pem
    networks:
      - docker-network
    depends_on:
      - nodejs

  nodejs:
    build: .
    container_name: 'tap-website-v1'
    image: tap-website:v1
    ports:
      - '3000:3000'
      - '8000:8000'
    environment:
      NODE_ENV: production
    restart: always
    networks:
      - docker-network

  tap-website-register:
    build: ../tap-registration
    container_name: 'tap-website-register-v1'
    image: tap-website-register:v1
    ports:
      - '3300:3300'
      - '8100:8100'
    environment:
      NODE_ENV: production
    restart: always
    networks:
      - docker-network


networks:
  docker-network:
    driver: bridge
